### ISSUE TITLE
Issues?

### ISSUE THREAD

**Issue by gdcmarinho** [danieloh30/quarkus-reactive-issues#1]
What you mean when you described the application hosted in this repository with the suffix "issues"? The README doesn't have a explanation about what you were studying about the Quarkus Reactive.

**Comment by danieloh30** [comment]
Don't get me wrong. This repo is not about reactive issues or bugs. Instead, I added some performance issues (e.g. @NonBlocking) for reactive apps which DEV UI shows the scores. This repo aims at how devs can solve potential performance issues in reactive apps with Quarkus.
